---
title: "RWorksheet_Llanera#4a"
author: "LlaneraExerRepo"
date: "2024-10-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.
A.
```{r}
shoe_size <- c(8, 9, 10, 6, 7)
height <- c(170, 180, 175, 160, 165)
gender <- c("M", "M", "M", "F", "F")

data <- data.frame(ShoeSize = shoe_size, Height = height, Gender = gender)
print(data)
```
B.
```{r}
male_data <- subset(data, Gender == "M")
female_data <- subset(data, Gender == "F")

print(male_data)
print(female_data)
```
C.
```{r}
# c
mean_shoe_size <- mean(data$ShoeSize)
mean_height <- mean(data$Height)

print(paste("Mean Shoe Size:", mean_shoe_size))
print(paste("Mean Height:", mean_height))
```
D.
```{r}
plot(data$ShoeSize, data$Height, main="Shoe Size vs Height", xlab="Shoe Size", ylab="Height")
```
2.
```{r}
monthsVector <- c("March", "April", "January", "November", "January", "September", "October", 
                   "September", "November", "August", "January", "November", "November", 
                   "February", "May", "August", "July", "December", "August", "August", 
                   "September", "November", "February", "April")


factorMonthsVector <- factor(monthsVector)
print(factorMonthsVector)
```
3.
```{r}
direction <- c("East", "West", "North", "West", "North")
frequency <- c(1, 4, 3, 2, 1)

factorDirection <- factor(direction, levels = c("East", "West", "North"))
print(factorDirection)

```
4. 
```{r}
factor_data <- c("East", "West", "North")
frequency_vector <- c(1, 4, 3)
new_order_data <- factor(factor_data,levels = c("East","West","North"))
print(new_order_data)
```

```{r}

plot(data$ShoeSize, data$Height, main="Shoe Size vs Height", xlab="Shoe Size", ylab="Height")
```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
